# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, model_validator

from . import fulfillment_destination, fulfillment_group


class FulfillmentMethod(BaseModel):
    """
    A fulfillment method with destinations and groups.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    """
    Unique fulfillment method identifier.
    """
    type: str
    """
    Fulfillment method type. Well-known values: `shipping`, `pickup`. Businesses MAY use additional values.
    """
    line_item_ids: list[str]
    """
    Line item IDs fulfilled via this method.
    """
    destinations: (
        list[fulfillment_destination.FulfillmentDestination] | None
    ) = None
    """
    Available destinations for this method. In Business responses, each destination carries a `type` and `id`.
    """
    selected_destination_id: str | None = None
    """
    ID of the selected destination. Accepts any stable, Business-scoped ID the Business recognizes for this method, including Location IDs not yet enumerated in `destinations`.
    """
    groups: list[fulfillment_group.FulfillmentGroup] | None = None
    """
    Fulfillment groups for selecting options. Agent sets selected_option_id on groups to choose shipping method.
    """

    @model_validator(mode="after")
    def _enforce_conditional_item_retyping(self):
        """JSON Schema if/then: approximate a discriminator's array-item
        retyping to a different referenced schema, via that schema's own
        required keys and const-pinned fields."""
        rules = [
            {
                "discriminator": "type",
                "values": ["shipping"],
                "field": "destinations",
                "required": ["id", "type"],
                "consts": {"type": "shipping_address"},
            },
            {
                "discriminator": "type",
                "values": ["pickup"],
                "field": "destinations",
                "required": ["type"],
                "consts": {"type": "business_location"},
            },
        ]
        for rule in rules:
            actual = getattr(self, rule["discriminator"], None)
            if actual not in rule["values"]:
                continue
            for _item in getattr(self, rule["field"], None) or []:
                _provided = (
                    set(_item.keys())
                    if isinstance(_item, dict)
                    else _item.model_fields_set | set(_item.model_extra or {})
                )
                for _required in rule["required"]:
                    if _required not in _provided:
                        raise ValueError(
                            f"Field {_required!r} is required for "
                            f"{rule['field']} items when "
                            f"{rule['discriminator']} is {actual!r}"
                        )
                for _const_field, _const_value in rule["consts"].items():
                    _actual_value = (
                        _item.get(_const_field)
                        if isinstance(_item, dict)
                        else getattr(_item, _const_field, None)
                    )
                    if _actual_value != _const_value:
                        raise ValueError(
                            f"Field {_const_field!r} must equal "
                            f"{_const_value!r} for {rule['field']} items "
                            f"when {rule['discriminator']} is {actual!r}"
                        )
        return self
