# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

import operator

from pydantic import BaseModel, ConfigDict, Field, model_validator

from . import ucp as ucp_1


class JwkPublicKey(BaseModel):
    """
    Public JSON Web Key used for HTTP Message Signatures and signed webhook verification. UCP profiles publish public keys only; private key material MUST NOT appear in a profile. Well-known key types: EC (ECDSA P-256, P-384) and OKP (EdDSA Ed25519); OKP keys are RECOMMENDED for signers opting into Web Bot Auth (WBA) interop on HTTP transport. A single profile MAY publish keys of either or both types; consumers select keys by kid. The kty, crv, and alg vocabularies are OPEN: verifiers MUST tolerate key types, curves, and algorithms they do not recognize, selecting keys by kid at verification time. An unsupported key affects only the signature that references it (algorithm_unsupported) and MUST NOT cause whole-profile rejection. Additional public JWK members are permitted; consumers ignore unknown members.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    kid: str
    """
    Key identifier referenced by Signature-Input keyid. For keys used in dual-audience (Web Bot Auth) signatures, the kid MUST be the key's JWK SHA-256 Thumbprint (RFC 7638) so UCP-Agent and Signature-Agent lookups resolve the same key; otherwise the kid MAY be any stable string.
    """
    kty: str = Field(..., examples=["EC", "OKP"])
    """
    JWK key type. Well-known values: EC for ECDSA (P-256, P-384); OKP for EdDSA (Ed25519). Open vocabulary; verifiers tolerate unrecognized types and select keys by kid.
    """
    crv: str | None = Field(None, examples=["P-256", "P-384", "Ed25519"])
    """
    Curve name. Well-known values: P-256, P-384 (EC); Ed25519 (OKP). Open vocabulary.
    """
    x: str | None = None
    """
    Public key value, base64url-encoded. For EC, the x coordinate (RFC 7518 §6.2); for OKP, the public key (RFC 8037 §2).
    """
    y: str | None = None
    """
    EC public key y coordinate, base64url-encoded (RFC 7518 §6.2). Not used by OKP keys.
    """
    alg: str | None = Field(None, examples=["ES256", "ES384", "EdDSA"])
    """
    JWA algorithm associated with this public key. Optional; verifiers derive the algorithm from crv when alg is omitted. When present for a well-known curve it MUST match: ES256 with P-256, ES384 with P-384, EdDSA with Ed25519.
    """
    use: str | None = None
    """
    JWK public key use. UCP examples use sig for signatures.
    """

    @model_validator(mode="after")
    def _enforce_conditional_required(self):
        """JSON Schema if/then: enforce conditionally required fields."""
        rules = [
            {
                "discriminator": "kty",
                "values": ["EC"],
                "required": ["crv", "x", "y"],
            },
            {
                "discriminator": "kty",
                "values": ["OKP"],
                "required": ["crv", "x"],
            },
        ]
        for rule in rules:
            if getattr(self, rule["discriminator"], None) not in rule["values"]:
                continue
            for field in rule["required"]:
                if field not in self.model_fields_set:
                    raise ValueError(
                        f"Field {field!r} is required by a schema condition"
                    )
        return self

    @model_validator(mode="after")
    def _enforce_conditional_bounds(self):
        """JSON Schema if/then: enforce conditional numeric bounds."""
        rules = [
            {
                "discriminator": "crv",
                "values": ["P-256"],
                "bounds": {"alg": {"const": "ES256"}},
            },
            {
                "discriminator": "crv",
                "values": ["P-384"],
                "bounds": {"alg": {"const": "ES384"}},
            },
            {
                "discriminator": "crv",
                "values": ["Ed25519"],
                "bounds": {"alg": {"const": "EdDSA"}},
            },
        ]
        checks = {
            "minimum": (">=", "lt"),
            "maximum": ("<=", "gt"),
            "exclusiveMinimum": (">", "le"),
            "exclusiveMaximum": ("<", "ge"),
            "const": ("==", "ne"),
        }
        for rule in rules:
            actual = getattr(self, rule["discriminator"], None)
            if actual not in rule["values"]:
                continue
            for field, bounds in rule["bounds"].items():
                value = getattr(self, field, None)
                if value is None:
                    continue
                for keyword, limit in bounds.items():
                    symbol, op_name = checks[keyword]
                    if getattr(operator, op_name)(value, limit):
                        raise ValueError(
                            f"Field {field!r} must be {symbol} {limit} "
                            f"when {rule['discriminator']} is {actual!r}"
                        )
        return self


class UcpProfileDocument(BaseModel):
    """
    Variant-neutral wrapper schema for UCP profile documents. Use the business_schema definition to validate business profiles and the platform_schema definition to validate platform profiles.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    ucp: ucp_1.Base
    """
    Protocol metadata, capabilities, services, and payment handlers advertised by this party.
    """
    keys: list[JwkPublicKey] | None = None
    """
    Canonical UCP profile field for publishing signing keys, as a JWK Set per RFC 7517. When a profile publishes signing keys, they MUST appear here; this is where every UCP verifier reads them. Publishing keys[] makes the UCP profile a valid JWK Set that a signer can reuse as its Web Bot Auth key source: a WBA-shape verifier resolving via Signature-Agent type=jwks_uri pointed at this profile reads these keys, and the cimd and directory variants reach them through their own documents. See the Deployment Patterns for WBA Interop section in the overview for hosting patterns.
    """


class Base(BaseModel):
    """
    Common wrapper for UCP profile documents.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    ucp: ucp_1.Base
    """
    Protocol metadata, capabilities, services, and payment handlers advertised by this party.
    """
    keys: list[JwkPublicKey] | None = None
    """
    Canonical UCP profile field for publishing signing keys, as a JWK Set per RFC 7517. When a profile publishes signing keys, they MUST appear here; this is where every UCP verifier reads them. Publishing keys[] makes the UCP profile a valid JWK Set that a signer can reuse as its Web Bot Auth key source: a WBA-shape verifier resolving via Signature-Agent type=jwks_uri pointed at this profile reads these keys, and the cimd and directory variants reach them through their own documents. See the Deployment Patterns for WBA Interop section in the overview for hosting patterns.
    """


class BusinessSchema(BaseModel):
    """
    Profile document hosted by a business at /.well-known/ucp.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    ucp: ucp_1.BusinessSchema
    keys: list[JwkPublicKey] | None = None
    """
    Canonical UCP profile field for publishing signing keys, as a JWK Set per RFC 7517. When a profile publishes signing keys, they MUST appear here; this is where every UCP verifier reads them. Publishing keys[] makes the UCP profile a valid JWK Set that a signer can reuse as its Web Bot Auth key source: a WBA-shape verifier resolving via Signature-Agent type=jwks_uri pointed at this profile reads these keys, and the cimd and directory variants reach them through their own documents. See the Deployment Patterns for WBA Interop section in the overview for hosting patterns.
    """


class PlatformSchema(BaseModel):
    """
    Profile document hosted by a platform and advertised to businesses via UCP-Agent.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    ucp: ucp_1.PlatformSchema
    keys: list[JwkPublicKey] | None = None
    """
    Canonical UCP profile field for publishing signing keys, as a JWK Set per RFC 7517. When a profile publishes signing keys, they MUST appear here; this is where every UCP verifier reads them. Publishing keys[] makes the UCP profile a valid JWK Set that a signer can reuse as its Web Bot Auth key source: a WBA-shape verifier resolving via Signature-Agent type=jwks_uri pointed at this profile reads these keys, and the cimd and directory variants reach them through their own documents. See the Deployment Patterns for WBA Interop section in the overview for hosting patterns.
    """
