# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, model_validator

from . import geo
from .locality import Locality


class Address(Locality):
    """
    Coarse locality of the service target.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    address_country: str = Field(..., min_length=1)


class Address1(Locality):
    """
    Coarse locality of the service target.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    address_region: str = Field(..., min_length=1)


class Address2(Locality):
    """
    Coarse locality of the service target.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    postal_code: str = Field(..., min_length=1)


class LocationServes(BaseModel):
    """
    A one-entry map whose key names the authoritative service-target representation. The Platform MUST supply exactly one target form. A Business that cannot evaluate a well-formed target, or receives an extension form that was not negotiated, MUST reject the request rather than ignore it, fall back, or broaden results. This dictionary-like representation map cannot host an ambient `ucp` member.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    point: geo.Geo | None = None
    """
    WGS 84 coordinates of the service target.
    """
    address: Address | Address1 | Address2 | None = None
    """
    Coarse locality of the service target.
    """

    @model_validator(mode="after")
    def _enforce_min_properties(self):
        """JSON Schema minProperties: require at least 1
        provided property."""
        provided = self.model_fields_set | set(self.model_extra or {})
        if len(provided) < 1:
            raise ValueError(
                "At least 1 property must be provided (schema minProperties=1)"
            )
        return self

    @model_validator(mode="after")
    def _enforce_max_properties(self):
        """JSON Schema maxProperties: allow at most 1
        provided property."""
        provided = self.model_fields_set | set(self.model_extra or {})
        if len(provided) > 1:
            raise ValueError(
                "At most 1 property may be provided (schema maxProperties=1)"
            )
        return self
