# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

import operator

from typing import Annotated

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    AfterValidator,
    model_validator,
)
from typing_extensions import TypeAliasType

from . import signed_amount
from .total import Total as Total_1


class Line(BaseModel):
    """
    Sub-line entry. Additional metadata MAY be included.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    display_text: str
    """
    Human-readable label for this sub-line.
    """
    amount: signed_amount.SignedAmount


class Total(Total_1):
    model_config = ConfigDict(
        extra="allow",
    )
    lines: list[Line] | None = None
    """
    Optional itemized breakdown. The parent entry is always rendered; lines are supplementary. Sum of line amounts MUST equal the parent entry amount.
    """

    @model_validator(mode="after")
    def _enforce_conditional_bounds(self):
        """JSON Schema if/then: enforce conditional numeric bounds."""
        rules = [
            {
                "discriminator": "type",
                "values": ["discount", "items_discount"],
                "bounds": {"amount": {"exclusiveMaximum": 0}},
            },
            {
                "discriminator": "type",
                "values": ["subtotal", "fulfillment", "tax", "fee"],
                "bounds": {"amount": {"minimum": 0}},
            },
        ]
        checks = {
            "minimum": (">=", "lt"),
            "maximum": ("<=", "gt"),
            "exclusiveMinimum": (">", "le"),
            "exclusiveMaximum": ("<", "ge"),
            "const": ("==", "ne"),
        }
        for rule in rules:
            actual = getattr(self, rule["discriminator"], None)
            if actual not in rule["values"]:
                continue
            for field, bounds in rule["bounds"].items():
                value = getattr(self, field, None)
                if value is None:
                    continue
                for keyword, limit in bounds.items():
                    symbol, op_name = checks[keyword]
                    if getattr(operator, op_name)(value, limit):
                        raise ValueError(
                            f"Field {field!r} must be {symbol} {limit} "
                            f"when {rule['discriminator']} is {actual!r}"
                        )
        return self


def _enforce_contains_totals(value):
    """JSON Schema contains/minContains/maxContains (see #49)."""
    _matched_0 = sum(
        1
        for _item in value
        if (
            _item.get("type")
            if isinstance(_item, dict)
            else getattr(_item, "type", None)
        )
        == "subtotal"
    )
    if _matched_0 < 1:
        raise ValueError(
            "Array must contain at least 1 entry "
            "matching type=='subtotal' (schema minContains=1)"
        )
    if _matched_0 > 1:
        raise ValueError(
            "Array must contain at most 1 entry "
            "matching type=='subtotal' (schema maxContains=1)"
        )
    _matched_1 = sum(
        1
        for _item in value
        if (
            _item.get("type")
            if isinstance(_item, dict)
            else getattr(_item, "type", None)
        )
        == "total"
    )
    if _matched_1 < 1:
        raise ValueError(
            "Array must contain at least 1 entry "
            "matching type=='total' (schema minContains=1)"
        )
    if _matched_1 > 1:
        raise ValueError(
            "Array must contain at most 1 entry "
            "matching type=='total' (schema maxContains=1)"
        )
    _excluded = [
        "subtotal",
        "items_discount",
        "discount",
        "fulfillment",
        "tax",
        "fee",
        "total",
    ]
    for _item in value:
        _actual = (
            _item.get("type")
            if isinstance(_item, dict)
            else getattr(_item, "type", None)
        )
        if _actual in _excluded:
            continue
        if isinstance(_item, dict) and "display_text" not in _item:
            raise ValueError("Field 'display_text' is required for custom type")
        if (
            not isinstance(_item, dict)
            and "display_text" not in _item.model_fields_set
        ):
            raise ValueError("Field 'display_text' is required for custom type")
    return value


Totals = TypeAliasType(
    "Totals",
    Annotated[
        list[Total],
        Field(..., title="Totals"),
        AfterValidator(_enforce_contains_totals),
    ],
)
"""
Pricing breakdown provided by the business. MUST contain exactly one subtotal and one total entry. Detail types (tax, fee, discount, fulfillment) may appear multiple times for itemization. Platforms MUST render all entries in order using display_text and amount.
"""
