# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

import operator

from pydantic import BaseModel, ConfigDict, Field, model_validator


class Unit(BaseModel):
    """
    A reusable unit descriptor for quantities and measures. Its unit-descriptor machine identity is (`unit`, effective `scale`), where effective `scale` is the provided `scale` or 0; `display_text` is excluded.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    unit: str
    """
    Stable machine identifier. The Business SHOULD use the exact UN/CEFACT Rec20 Common Code when one accurately identifies the unit. Otherwise, the Business MAY use a custom unit identifier and MUST use it consistently for the same unit. The Platform MUST treat an unrecognized identifier as opaque.
    """
    scale: int | None = Field(0, ge=0, le=15)
    """
    One step equals `10^-scale` of `unit`. When `unit` is `C62`, `scale`, if present, MUST be 0. The maximum of 15 is derived from the interoperable integer range: at scale 16 a single whole unit (10^16 steps) is no longer representable, so larger scales cannot denominate one unit of their own basis. Businesses needing finer granularity use a smaller unit.
    """
    display_text: str
    """
    Required printable unit label provided by the Business. The Platform MUST use it when it does not recognize `unit`; for a recognized UN/CEFACT Rec 20 Common Code, the Platform MAY substitute its own localized label. It does not participate in unit identity or mismatch comparison.
    """

    @model_validator(mode="after")
    def _enforce_conditional_bounds(self):
        """JSON Schema if/then: enforce conditional numeric bounds."""
        rules = [
            {
                "discriminator": "unit",
                "values": ["C62"],
                "bounds": {"scale": {"const": 0}},
            }
        ]
        checks = {
            "minimum": (">=", "lt"),
            "maximum": ("<=", "gt"),
            "exclusiveMinimum": (">", "le"),
            "exclusiveMaximum": ("<", "ge"),
            "const": ("==", "ne"),
        }
        for rule in rules:
            actual = getattr(self, rule["discriminator"], None)
            if actual not in rule["values"]:
                continue
            for field, bounds in rule["bounds"].items():
                value = getattr(self, field, None)
                if value is None:
                    continue
                for keyword, limit in bounds.items():
                    symbol, op_name = checks[keyword]
                    if getattr(operator, op_name)(value, limit):
                        raise ValueError(
                            f"Field {field!r} must be {symbol} {limit} "
                            f"when {rule['discriminator']} is {actual!r}"
                        )
        return self
